jobs:
  deploy-snapshot:
    if: ${{ success() }}
    needs: test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.2.0
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '8'
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Cache m2 package
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: setting snapshot version
      run: "import xml.etree.ElementTree as ET\ntree = ET.parse(\"pom.xml\")\nversion\
        \ = tree.find(\"{http://maven.apache.org/POM/4.0.0}version\")\nprint(version.text\
        \ + \"-SNAPSHOT\")\nif version.text.endswith(\"-SNAPSHOT\") == False:\n  tree.find(\"\
        {http://maven.apache.org/POM/4.0.0}version\").text = version.text + \"-SNAPSHOT\"\
        \n  ET.register_namespace(\"\", \"http://maven.apache.org/POM/4.0.0\")\n \
        \ tree.write(\"pom.xml\", \"utf-8\", True)\n"
      shell: python
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: deploy snapshot to ossrh repository
      run: mvn -B deploy -P snapshot -DskipTests
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.2.0
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      name: Cache m2 package
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      run: mvn test
name: Deploy
on:
  repository_dispatch:
    types: trigger-ga___deploy-snapshot.yml
