jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.2.0
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      name: Cache m2 package
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      run: mvn test
name: test pull_request
on:
  repository_dispatch:
    types: trigger-ga___test-pr.yml
